import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the datasets
customers_df = pd.read_csv('/content/Customers.csv')
products_df = pd.read_csv('/content/Products.csv')
transactions_df = pd.read_csv('/content/Transactions.csv')
customers_df['SignupDate'] = pd.to_datetime(customers_df['SignupDate'])
transactions_df['TransactionDate'] = pd.to_datetime(transactions_df['TransactionDate'])
customer_region_counts = customers_df['Region'].value_counts()
plt.figure(figsize=(8, 5))
sns.countplot(data=customers_df, y='Region', order=customer_region_counts.index, palette='viridis')
plt.title('Customer Distribution by Region')
plt.xlabel('Count')
plt.ylabel('Region')
plt.show()
product_category_counts = products_df['Category'].value_counts()
plt.figure(figsize=(8, 5))
sns.barplot(y=product_category_counts.index, x=product_category_counts.values, palette='plasma')
plt.title('Product Distribution by Category')
plt.xlabel('Count')
plt.ylabel('Category')
plt.show()
transaction_trend = transactions_df.resample('M', on='TransactionDate').size()
plt.figure(figsize=(10, 5))
transaction_trend.plot(kind='line', color='teal')
plt.title('Monthly Transaction Volume')
plt.xlabel('Month')
plt.ylabel('Number of Transactions')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
top_customers = transactions_df.groupby('CustomerID')['TotalValue'].sum().nlargest(5)
print("Top 5 Customers by Total Spending:")
print(top_customers)
top_products = transactions_df.groupby('ProductID')['Quantity'].sum().nlargest(5)
print("Top 5 Products by Quantity Sold:")
print(top_products)
